name: Run Newman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run Newman tests
      run: npm test

    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: newman/newman-report.html

    - name: Send report via email
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        curl -X POST "https://api.sendgrid.com/v3/mail/send" \
        -H "Authorization: Bearer $SENDGRID_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{
          "personalizations": [
            {
              "to": [{ "email": "ihsan@vaultn.com" }],
              "subject": "Newman Test Report"
            }
          ],
          "from": { "email": "ihsan@vaultn.com" },
          "content": [
            {
              "type": "text/html",
              "value": "<p>Newman test report attached.</p>"
            }
          ],
          "attachments": [
            {
              "content": "'"$(base64 newman/newman-report.html)"'",
              "type": "text/html",
              "filename": "report.html"
            }
          ]
        }'
